#!/bin/bash
echo -e "\033[1;36m INI INFORMASI ANDA!\033[0m"
echo ""
echo -ne "SEU NS (Nameserver): " && cat /etc/slowdns/infons
echo ""
echo -ne "SUA KEY: " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mPERINTAH TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m KUNCI ANDA disimpan dalam file /root/server.pub\033[0m"
echo -e "\033[1;33mSimpan di tempat yang aman, Anda mungkin membutuhkannya di masa depan!\033[0m"
echo ""
read -p "Tekan [Enter] untuk kembali ke menu atau CTRL+C untuk keluar"
slowdns
