#!/bin/bash
clear
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mTUNGGU \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mTUNGGU \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "INSTALL SLOWDNS DROPBEAR" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo -e ""
echo -e "      Script ini akan menginstal"
echo -e " slowdns untuk tunneling DNS dengan Dropbear."
echo -e ""
echo -e "         \033[1;33mPemasang dibuat berdasarkan edisi ️ \033[1;37m"
echo -e ""
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "PERBARUI DAFTAR PAKET..."
fun_att () {
apt update && apt upgrade -y
}
fun_bar 'fun_att'
echo -e "MENGINSTAL DAN MEMPERBARUI PAKET YANG DIPERLUKAN..."
install_pkgs () {
apt install screen -y
apt install cron -y
apt install iptables -y
service cron reload
service cron restart
service iptables reload
service iptables restart
}
fun_bar 'install_pkgs'
echo -e "UNDUH BINARY DNSTT..."
download_dnstt () {
rm -rf /etc/slowdns
mkdir /etc/slowdns
cd /etc/slowdns/ && wget https://github.com/fisabiliyusri/Mantap/Slowdns/raw/main/Slowdns/dns-server
chmod +x dns-server
}
fun_bar 'download_dnstt'
echo -e "MENGONFIGURASI IPTABLES..."
ipt_set () {
cd /etc
rm -rf rc.local
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/rc.local
chmod +x /etc/rc.local
systemctl enable rc-local
systemctl start rc-local
}
fun_bar 'ipt_set'
clear
echo ""
echo -e "\033[1;31m PERHATIAN DALAM TAHAP INI! \033[1;33m"
echo ""
echo -ne "\033[1;32m INFORMASIKAN NS ANDA (NAMESERVER)\033[1;37m: "; read nameserver
cd /etc/slowdns
touch infons
echo $nameserver > infons
set_ns () {
sleep 1
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/drop/startdns
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/drop/restartdns
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/slowdns-info
chmod +x startdns
chmod +x restartdns
sed -i "s;0.0.0.0;$nameserver;g" /etc/slowdns/startdns > /dev/null 2>&1
sed -i "s;0.0.0.0;$nameserver;g" /etc/slowdns/restartdns > /dev/null 2>&1
cp startdns /bin/
cp restartdns /bin/
}
fun_bar 'set_ns'
echo ""
echo "Memeriksa keberadaan kunci"
sleep 2
echo ""
echo "      Tunggu sebentar...   "
sleep 2
cd
key1="/root/server.key"
key2="/root/server.pub"
if [ -f $key1 ] && [ -f $key2 ]
then
echo -e "File kunci ditemukan!"
sleep 1
echo ""
key () {
echo "Bagaimana Anda ingin mendapatkan kunci Anda?"
echo ""
echo "[ 1 ] | Gunakan kunci yang ada dalam file"
echo "[ 2 ] | Hapus file dan buat kunci baru"
echo "[ 3 ] | Hapus file dan gunakan kunci default"
echo "[ x ] | batalkan pemasangan"
echo ""
echo -ne "Masukkan opsi: " && read opcao
case $opcao in
1) Opcao1 ;;
2) Opcao2 ;;
3) Opcao3 ;;
x) OpcaoX ;;
*) "Calma Barboleta" ; echo ; key;;
esac
}
Opcao1 () {
echo -ne "Memulihkan kunci yang ada..." && sleep 2 && echo "OK!"
echo ""
echo -e "SELESAI..."
finish_ist () {
cd /etc/slowdns
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m PEMASANGAN SELESAI!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mPERINTAH TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m KUNCI ANDA disimpan dalam file /root/server.pub\033[0m"
echo -e "\033[1;33mSimpan di tempat yang aman, Anda mungkin membutuhkannya di masa depan.!\033[0m"
echo ""
read -p "Tekan [Enter] untuk kembali ke menu atau CTRL+C untuk keluar"
slowdns
}
Opcao2 () {
cd
rm server.key server.pub
echo "Menghasilkan kunci baru"
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "SELESAI..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m KUNCI ANDA disimpan dalam file /root/server.pub\033[0m"
echo -e "\033[1;33mSimpan di tempat yang aman, Anda mungkin membutuhkannya di masa depan!\033[0m"
echo ""
read -p "Tekan [Enter] untuk kembali ke menu atau CTRL+C untuk keluar"
slowdns
}
Opcao3 () {
echo -e "Baixando par de chaves padrão..."
cd
rm server.key server.pub
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/server.key
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/server.pub
sleep 1
echo -e "Download Concluído"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m KUNCI ANDA disimpan dalam file /root/server.pub\033[0m"
echo -e "\033[1;33mSimpan di tempat yang aman, Anda mungkin membutuhkannya di masa depan.!\033[0m"
echo ""
read -p "Tekan [Enter] untuk kembali ke menu atau CTRL+C untuk keluar"
slowdns
}
OpcaoX () {
exit
}
key
else
echo -e "Não existe uma key nos registros"
echo ""
key_gen () {
echo "Como deseja obter sua key?"
echo ""
echo "[ 1 ] | Gerar na instalação"
echo "[ 2 ] | Usar a key padrão"
echo "[ x ] | Abortar instalação"
echo ""
echo -ne "Digite uma opção: " && read opc_key
case $opc_key in
1) opc_key1 ;;
2) opc_key2 ;;
x) opc_keyx ;;
*) "Comando desconhecido" ; echo ; key_gen;;
esac
}
opc_key1 () {
echo "Gerando sua key..."
cd /etc/slowdns/
./dns-server -gen-key -privkey-file /root/server.key -pubkey-file /root/server.pub
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m KUNCI ANDA disimpan dalam file /root/server.pub\033[0m"
echo -e "\033[1;33mSimpan di tempat yang aman, Anda mungkin membutuhkannya di masa depan.!\033[0m"
echo ""
read -p "Tekan [Enter] untuk kembali ke menu atau CTRL+C untuk keluar"
slowdns
}
opc_key2 () {
echo -e "Baixando par de chaves padrão..."
cd
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/server.key
wget https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Slowdns/server.pub
sleep 1
echo -e "Download Concluído"
sleep 1
cd /etc/slowdns/
echo -e "FINALIZANDO..."
finish_ist () {
iptables -I INPUT -p udp --dport 5300 -j ACCEPT
iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5300
./startdns
cd
}
fun_bar 'finish_ist'
clear
echo -e "\033[1;31m INSTALAÇÃO CONCLUÍDA!\033[0m"
echo ""
echo -ne "\033[1;33mSEU NS:\033[0m " && cat /etc/slowdns/infons
echo ""
echo -ne "\033[1;33mSUA KEY:\033[0m " && cat /root/server.pub
echo ""
echo -ne "\033[1;33mCOMANDO TERMUX:\033[0m curl -sO https://raw.githubusercontent.com/fisabiliyusri/Mantap/Slowdns/main/Install/slowdns && chmod +x slowdns && ./slowdns " && cat /etc/slowdns/infons /root/server.pub
echo ""
echo -e "\033[1;33m KUNCI ANDA disimpan dalam file /root/server.pub\033[0m"
echo -e "\033[1;33mSimpan di tempat yang aman, Anda mungkin membutuhkannya di masa depan.!\033[0m"
echo ""
read -p "Tekan [Enter] untuk kembali ke menu atau CTRL+C untuk keluar"
slowdns
}
opc_keyx () {
echo "Membatalkan pemasangan"
sleep 2
slowdns
}
key_gen
fi
